Repository HardikPanwar/Hacktoberfest_Starter_2k23, pull requests merged in 2023-10, with the labels that each got.

#20 Described about my tech details
  contributors/Participants/simran.md
Labels: hacktoberfest-accepted

#1 Added My Details
  contributors/Participants/Prasanna.md
Labels: hacktoberfest-accepted

#8 Added my info
  contributors/Participants/Krish.md
Labels: hacktoberfest-accepted

#7 Added my detailed information
  contributors/Participants/Tanishq.md
Labels: hacktoberfest-accepted

#3 Added my information
  contributors/Participants/vijay.md
Labels: hacktoberfest-accepted

#5 Added My info
  contributors/Participants/Sumit.md
Labels: documentation, hacktoberfest-accepted

#6 Added My info
  contributors/Participants/Nandini.md
Labels: documentation, hacktoberfest-accepted

#9 added my details
  contributors/Participants/vasu.md
Labels: hacktoberfest-accepted

#15 updated my profile
  contributors/Participants/divyansh.md
Labels: documentation, hacktoberfest-accepted

#18 Added my info
  contributors/Participants/adesh.md
Labels: hacktoberfest-accepted

#21 Added My Details
  contributors/Participants/Zoya_qureshi.md
Labels: hacktoberfest-accepted

#22 Update the code
  contributors/Participants/bhavya.md
Labels: hacktoberfest-accepted

#28 Add files via upload
  assets/Images/5.png
  contributors/Participants/Ayush.md
Labels: documentation, enhancement, hacktoberfest-accepted
